question_data = [
{"text": "A slug's blood is green.", "answer": "True"},
{"text": "The loudest animal is the African Elephant.", "answer": "False"},
{"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
{"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
{"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
{"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
{"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
{"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
{"text": "Google was originally called 'Backrub'.", "answer": "True"},
{"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
{"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
{"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
{"text": "Bananas are berries, but strawberries are not.", "answer": "True"},
{"text": "Humans and giraffes have the same number of neck vertebrae.", "answer": "True"},
{"text": "The Great Wall of China is visible from space.", "answer": "False"},
{"text": "Octopuses have three hearts.", "answer": "True"},
{"text": "Venus is the hottest planet in our solar system.", "answer": "True"},
{"text": "The capital of Australia is Sydney.", "answer": "False"},
{"text": "The human body has four lungs.", "answer": "False"},
{"text": "Goldfish only have a memory of three seconds.", "answer": "False"},
{"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
{"text": "Bats are blind.", "answer": "False"},
{"text": "Sharks are mammals.", "answer": "False"},
{"text": "Electrons are larger than molecules.", "answer": "False"},
{"text": "The Atlantic Ocean is the largest ocean on Earth.", "answer": "False"},
{"text": "Mount Everest is the tallest mountain in the world.", "answer": "True"},
{"text": "There are more stars in the universe than grains of sand on all the world's beaches.", "answer": "True"},
{"text": "The Mona Lisa was painted by Vincent van Gogh.", "answer": "False"},
{"text": "The currency of Japan is the Yen.", "answer": "True"},
{"text": "Spiders are insects.", "answer": "False"},
{"text": "A day on Venus is longer than a year on Venus.", "answer": "True"},
{"text": "The human nose can detect over 1 trillion different scents.", "answer": "True"},
{"text": "Cows have four stomachs.", "answer": "True"},
{"text": "The longest river in the world is the Amazon River.", "answer": "False"},
{"text": "Humans can breathe and swallow at the same time.", "answer": "False"},
{"text": "The hardest substance in the human body is enamel.", "answer": "True"},
{"text": "Light travels faster than sound.", "answer": "True"},
{"text": "Peanuts are a type of nut.", "answer": "False"},
{"text": "Penguins can fly.", "answer": "False"},
{"text": "The Eiffel Tower is located in Rome.", "answer": "False"},
{"text": "Honey never spoils.", "answer": "True"},
{"text": "Humans share approximately 60% of their DNA with bananas.", "answer": "True"},
{"text": "A sneeze can exceed the speed of 100 miles per hour.", "answer": "True"},
{"text": "A group of crows is called a murder.", "answer": "True"},
{"text": "There are seven colors in a rainbow.", "answer": "True"},
{"text": "The smallest bone in the human body is the stapes, located in the ear.", "answer": "True"},
{"text": "The Earth is the center of the universe.", "answer": "False"},
{"text": "There are 206 bones in the adult human body.", "answer": "True"},
{"text": "Humans can survive without water for a week.", "answer": "False"},
{"text": "The chemical symbol for gold is Au.", "answer": "True"},
{"text": "The capital of Canada is Toronto.", "answer": "False"},
{"text": "The sun is a star.", "answer": "True"},
{"text": "Humans use only 10% of their brains.", "answer": "False"},
{"text": "Venus is the closest planet to the sun.", "answer": "False"},
{"text": "The longest bone in the human body is the femur.", "answer": "True"},
{"text": "Birds are mammals.", "answer": "False"},
{"text": "The Great Wall of China was built in a single year.", "answer": "False"},
{"text": "The Statue of Liberty was a gift from France to the United States.", "answer": "True"},
{"text": "Mercury is the only metal that is liquid at room temperature.", "answer": "True"},
{"text": "Thomas Edison invented the light bulb.", "answer": "False"},
{"text": "Diamonds are the hardest natural substance on Earth.", "answer": "True"},
{"text": "The human eye can see ultraviolet light.", "answer": "False"}
]